//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinMaster
    {
        public int Id { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string LocationName { get; set; }
        public string MSP { get; set; }
        public string IFSCCode { get; set; }
        public string ProductType { get; set; }
        public string CompanyCode { get; set; }
        public string Bank { get; set; }
        public string BinCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string HubLocationName { get; set; }
    }
}
