//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCallLogDetail
    {
        public decimal CallNo { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string AccountName { get; set; }
        public Nullable<decimal> CashLimit { get; set; }
        public string ClientCode { get; set; }
        public string CustomerUniqueId { get; set; }
        public string DivisionCode { get; set; }
        public string HierarchyCode { get; set; }
        public string OtherDetail1 { get; set; }
        public string OtherDetail2 { get; set; }
        public string OtherDetail3 { get; set; }
        public string OtherDetail4 { get; set; }
        public string OtherDetail5 { get; set; }
        public string OtherDetail6 { get; set; }
        public string OtherDetail7 { get; set; }
        public string OtherDetail8 { get; set; }
        public string PickupCode { get; set; }
        public string StoreCode { get; set; }
        public string SubCode { get; set; }
        public string SubDivisionCode { get; set; }
        public string AltMobileNo { get; set; }
        public string ContactName { get; set; }
        public string EmailID { get; set; }
        public string FaxNo { get; set; }
        public string MobileNo { get; set; }
        public string TelNo { get; set; }
        public Nullable<bool> AcceptClientSysGenDepositeSlip { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string AreaAsPerLOI { get; set; }
        public Nullable<bool> BarCode { get; set; }
        public Nullable<bool> CaptureClientRefNo { get; set; }
        public Nullable<bool> CashCounting { get; set; }
        public Nullable<bool> CashCountingVer { get; set; }
        public Nullable<bool> CashMerging { get; set; }
        public string CityAsPerLOI { get; set; }
        public string ClientGroupCode { get; set; }
        public string ClientSubGroupCode { get; set; }
        public string ClientSubSubGroupCode { get; set; }
        public Nullable<bool> Depositeslip { get; set; }
        public string DepositSlipPISType { get; set; }
        public string DistrictCode { get; set; }
        public string EntityAsPerLOI { get; set; }
        public Nullable<bool> HCINFlag { get; set; }
        public Nullable<bool> ImageSaving { get; set; }
        public string Industry { get; set; }
        public string IndustryName { get; set; }
        public string MarketClusterArea { get; set; }
        public Nullable<int> MPIN { get; set; }
        public Nullable<System.TimeSpan> NormalPickupFromTime { get; set; }
        public Nullable<System.TimeSpan> NormalPickupToTime { get; set; }
        public string PinCode { get; set; }
        public Nullable<bool> SameDayDeposit { get; set; }
        public Nullable<bool> SealBagPickup { get; set; }
        public Nullable<bool> SealbagProcessing { get; set; }
        public Nullable<System.TimeSpan> SLAFromTime { get; set; }
        public Nullable<System.TimeSpan> SLAToTime { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string TimeSpecificPickup { get; set; }
        public string TxnVerificationMode { get; set; }
        public Nullable<bool> Vaulting { get; set; }
        public string Zone { get; set; }
        public string AccountType { get; set; }
        public string CityLimitType { get; set; }
        public string ClientCustName { get; set; }
        public Nullable<decimal> CMSCashLimit { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> FarBCLkm { get; set; }
        public string HubLocationCode { get; set; }
        public string LandMark { get; set; }
        public Nullable<bool> MatchRequestAmount { get; set; }
        public Nullable<decimal> MaxCashLimit { get; set; }
        public string OldReferenceCode { get; set; }
        public string CustomerName { get; set; }
        public string HubLocationName { get; set; }
        public string LocationCode { get; set; }
        public string AreaName { get; set; }
        public string LocationName { get; set; }
        public string RegionName { get; set; }
        public string RouteCode { get; set; }
        public string SubLocationName { get; set; }
        public string ClientGroupName { get; set; }
        public string ClientSubSubGroupName { get; set; }
        public string ClientSubGroupName { get; set; }
        public string DepositionType { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<int> ClientAccountID { get; set; }
        public string SchemeName { get; set; }
        public string SchemeDetails { get; set; }
        public string ZoneName { get; set; }
        public string DistrictName { get; set; }
        public string FundingLocation { get; set; }
        public string DepositeDay { get; set; }
        public string txnApprovalMode { get; set; }
        public string ImagePath { get; set; }
        public string CDPPullingARG { get; set; }
        public string FundPullingARG { get; set; }
        public string SecretKey { get; set; }
        public Nullable<int> Priority_Id { get; set; }
        public string Priority_Type { get; set; }
        public Nullable<bool> flagScanAmount { get; set; }
        public string CMSDetail8 { get; set; }
    }
}
