//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallDenomination
    {
        public int id { get; set; }
        public decimal CallNo { get; set; }
        public System.DateTime GenDate { get; set; }
        public string ChildCRNno { get; set; }
        public Nullable<decimal> SerialNo { get; set; }
        public string AccountId { get; set; }
        public string ClientCode { get; set; }
        public string PickupCode { get; set; }
        public string StoreCode { get; set; }
        public string HierarchyCode { get; set; }
        public string DivisionCode { get; set; }
        public string SubDivisionCode { get; set; }
        public string SubCode { get; set; }
        public string CustomerDeptCode { get; set; }
        public Nullable<int> Deno1000 { get; set; }
        public Nullable<int> Deno2000 { get; set; }
        public Nullable<int> Deno500 { get; set; }
        public Nullable<int> Deno200 { get; set; }
        public Nullable<int> Deno100 { get; set; }
        public Nullable<int> Deno50 { get; set; }
        public Nullable<int> Deno20 { get; set; }
        public Nullable<int> Deno10 { get; set; }
        public Nullable<decimal> DenoOthers { get; set; }
        public string DepositSlipNo { get; set; }
        public string PISNo { get; set; }
        public string RTFNo { get; set; }
        public Nullable<decimal> PickupAmont { get; set; }
        public Nullable<decimal> PickupDifference { get; set; }
        public Nullable<decimal> DiscrepancyInCash { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OtherDetails1 { get; set; }
        public string OtherDetails2 { get; set; }
        public Nullable<int> DenoCoin10 { get; set; }
        public string Remarks_DP { get; set; }
        public string Remarks_PIS { get; set; }
        public string AccountFlag { get; set; }
        public Nullable<decimal> RequestAmount { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> RequestInfoDiffAmt { get; set; }
        public string CustomerUniqueId { get; set; }
        public string Remark_DPAgainstRule { get; set; }
        public string Remark_PISAgainstRule { get; set; }
        public Nullable<decimal> CashLimit { get; set; }
        public string FlagCashLimit { get; set; }
        public string FlagDP { get; set; }
        public string FlagPIS { get; set; }
        public string FlagDPRule { get; set; }
        public string FlagPISRule { get; set; }
        public string DepositSlipImage { get; set; }
        public string FlagDPReplace { get; set; }
        public string PISImage { get; set; }
        public string FlagPISReplace { get; set; }
        public string FlagRefNo { get; set; }
        public string CompanyCode { get; set; }
        public string FlagDepositUpload { get; set; }
        public string FlagPISUpload { get; set; }
        public Nullable<int> Deno5 { get; set; }
        public Nullable<int> Deno2 { get; set; }
        public string RTFImage { get; set; }
        public Nullable<int> callId { get; set; }
        public Nullable<int> ImgaeId { get; set; }
        public string FlagRefNoRule { get; set; }
        public string FlagRefmandatory { get; set; }
        public Nullable<int> ClientCustAccountMasterID { get; set; }
    }
}
