//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashDepositTxn
    {
        public int Id { get; set; }
        public decimal CallNo { get; set; }
        public string DepositSlipNo { get; set; }
        public string DepositType { get; set; }
        public string DepositionBank { get; set; }
        public string CRNNo { get; set; }
        public string ChildCRNno { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string VaultID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string NCM { get; set; }
        public string NCMAccountNo { get; set; }
        public string CDP { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<System.DateTime> GenDate { get; set; }
        public string FlagCDPDeposition { get; set; }
        public string FlagNCMDeposition { get; set; }
        public string FlagVaultDepositionCDP { get; set; }
        public string FlagVaultDepositionNCM { get; set; }
        public string FlagCDPDepositionDay01 { get; set; }
        public string FlagCDPDepositionDay02 { get; set; }
        public string FlagNCMDepositionDay01 { get; set; }
        public string FlagNCMDepositionDay02 { get; set; }
        public string BatchDSNo { get; set; }
        public Nullable<int> CorebankaccNo { get; set; }
        public string Flag { get; set; }
        public string Cashdepositflag { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string apisent { get; set; }
    }
}
