//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RNNCMDepositionTxnDetail
    {
        public long Id { get; set; }
        public long RNNCMDepsotionTxnId { get; set; }
        public Nullable<long> RNTransactionId { get; set; }
        public Nullable<int> LocalBankId { get; set; }
        public Nullable<int> VaultId { get; set; }
        public Nullable<int> NCMModeId { get; set; }
        public string Remark { get; set; }
        public decimal DepositedAmt { get; set; }
        public Nullable<bool> Obsolete { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CentralBankId { get; set; }
        public string flagapisent { get; set; }
    }
}
