//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaultMapping
    {
        public int Id { get; set; }
        public int RCMVaultId { get; set; }
        public int MDMVaultid { get; set; }
    }
}
